Repository HDInnovations/UNIT3D, pull requests merged in 2020-04, with the labels that each got.

#1256 (Add) Subtitle System
  app/Achievements/UserUploaded1000Subtitles.php
  app/Achievements/UserUploaded100Subtitles.php
  app/Achievements/UserUploaded200Subtitles.php
  app/Achievements/UserUploaded25Subtitles.php
  app/Achievements/UserUploaded300Subtitles.php
  app/Achievements/UserUploaded400Subtitles.php
  app/Achievements/UserUploaded500Subtitles.php
  app/Achievements/UserUploaded50Subtitles.php
  app/Achievements/UserUploaded600Subtitles.php
  app/Achievements/UserUploaded700Subtitles.php
  app/Achievements/UserUploaded800Subtitles.php
  app/Achievements/UserUploaded900Subtitles.php
  app/Achievements/UserUploadedFirstSubtitle.php
  app/Http/Controllers/Staff/MediaLanguageController.php
  app/Http/Controllers/SubtitleController.php
  app/Http/Controllers/TorrentController.php
  app/Models/MediaLanguage.php
  app/Models/Subtitle.php
  app/Models/Torrent.php
  config/filesystems.php
  database/migrations/2020_03_26_030235_create_subtitles_table.php
  database/migrations/2020_03_26_034620_create_media_languages_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/MediaLanguagesSeeder.php
  public/img/badges/UserUploaded1000Subtitles.png
  public/img/badges/UserUploaded100Subtitles.png
  public/img/badges/UserUploaded200Subtitles.png
  public/img/badges/UserUploaded25Subtitles.png
  public/img/badges/UserUploaded300Subtitles.png
  public/img/badges/UserUploaded400Subtitles.png
  public/img/badges/UserUploaded500Subtitles.png
  public/img/badges/UserUploaded50Subtitles.png
  public/img/badges/UserUploaded600Subtitles.png
  public/img/badges/UserUploaded700Subtitles.png
  public/img/badges/UserUploaded800Subtitles.png
  public/img/badges/UserUploaded900Subtitles.png
  public/img/badges/UserUploadedFirstSubtitle.png
  resources/lang/en/common.php
  resources/views/Staff/media_language/create.blade.php
  resources/views/Staff/media_language/edit.blade.php
  resources/views/Staff/media_language/index.blade.php
  resources/views/partials/dashboardmenu.blade.php
  resources/views/subtitle/create.blade.php
  resources/views/subtitle/modals.blade.php
  resources/views/torrent/partials/subtitles.blade.php
  resources/views/torrent/torrent.blade.php
  routes/web.php
Labels: Feature

#1296 (Update) Greek Localization
  resources/lang/el/auth.php
  resources/lang/el/backup.php
  resources/lang/el/blocks.php
  resources/lang/el/bon.php
  resources/lang/el/bot.php
  resources/lang/el/bug.php
  resources/lang/el/common.php
  resources/lang/el/email.php
  resources/lang/el/forum.php
  resources/lang/el/graveyard.php
  resources/lang/el/notification.php
  resources/lang/el/page.php
  resources/lang/el/pagination.php
  resources/lang/el/pm.php
  resources/lang/el/poll.php
  resources/lang/el/request.php
  resources/lang/el/rss.php
  resources/lang/el/staff.php
  resources/lang/el/stat.php
Labels: Translation

#1307 (Refactor) Multiple Code Style Changes
  app/Bots/CasinoBot.php
  app/Bots/IRCAnnounceBot.php
  app/Bots/NerdBot.php
  app/Bots/SystemBot.php
  app/Console/Commands/AutoNerdStat.php
  app/Console/Commands/AutoPreWarning.php
  app/Console/Commands/AutoRecycleClaimedTorrentRequests.php
  app/Console/Commands/AutoWarning.php
  app/Console/Commands/ClearCache.php
  app/Console/Commands/GitUpdater.php
  app/Console/Commands/SetCache.php
  app/Console/Commands/VendorCleanup.php
  app/Console/ConsoleTools.php
  app/Helpers/BBCodeConverter.php
  app/Helpers/BackupPassword.php
  app/Helpers/Bbcode.php
  app/Helpers/Helpers.php
  app/Helpers/LanguageCensor.php
  app/Helpers/Linkify.php
  app/Helpers/Markdown.php
  app/Helpers/MediaInfo.php
  app/Helpers/SystemInformation.php
  app/Http/Controllers/API/ChatController.php
  app/Http/Controllers/AlbumController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/TwoStepController.php
  app/Http/Controllers/BonusController.php
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/InviteController.php
  app/Http/Controllers/PollController.php
  app/Http/Controllers/RequestController.php
  app/Http/Controllers/RssController.php
  app/Http/Controllers/Staff/ChatBotController.php
  app/Http/Controllers/Staff/PollController.php
  app/Http/Controllers/Staff/RssController.php
  app/Http/Controllers/SubtitleController.php
  app/Http/Controllers/TopicController.php
  app/Http/Controllers/TorrentController.php
  app/Http/Controllers/UserController.php
  app/Http/Middleware/HtmlEncrypt.php
  app/Http/Middleware/Http2ServerPush.php
  app/Listeners/AchievementUnlocked.php
  app/Models/Forum.php
  app/Models/Topic.php
  app/Repositories/ChatRepository.php
  app/Services/Clients/MangaUpdatesClient.php
  app/Services/Data/Genre.php
  app/Services/Data/Movie.php
  app/Services/Data/Tv.php
Labels: Refactor, Review
