Repository HDInnovations/UNIT3D, pull requests merged in 2020-02, with the labels that each got.

#1122 Improve zh-CN translations.
  resources/lang/zh-CN/articles.php
  resources/lang/zh-CN/auth.php
  resources/lang/zh-CN/backup.php
  resources/lang/zh-CN/blocks.php
  resources/lang/zh-CN/bon.php
  resources/lang/zh-CN/bot.php
  resources/lang/zh-CN/bug.php
  resources/lang/zh-CN/common.php
  resources/lang/zh-CN/email.php
  resources/lang/zh-CN/forum.php
  resources/lang/zh-CN/graveyard.php
  resources/lang/zh-CN/notification.php
  resources/lang/zh-CN/page.php
  resources/lang/zh-CN/passwords.php
  resources/lang/zh-CN/pm.php
  resources/lang/zh-CN/poll.php
  resources/lang/zh-CN/request.php
  resources/lang/zh-CN/rss.php
  resources/lang/zh-CN/staff.php
  resources/lang/zh-CN/stat.php
  resources/lang/zh-CN/torrent.php
  resources/lang/zh-CN/user.php
  resources/lang/zh-CN/validation.php
Labels: Translation

#1117 Announce Refactor
  app/Http/Controllers/AnnounceController.php
  app/Observers/TorrentObserver.php
  app/Observers/UserObserver.php
  app/Providers/AppServiceProvider.php
Labels: Enhancement

#1124 (Refactor) if / else / elseif statements
  app/Bots/CasinoBot.php
  app/Bots/NerdBot.php
  app/Bots/SystemBot.php
  app/Helpers/Bencode.php
  app/Helpers/Linkify.php
  app/Helpers/Markdown.php
  app/Helpers/StringHelper.php
  app/Http/Controllers/API/TorrentController.php
  app/Http/Controllers/AlbumController.php
  app/Http/Controllers/AnnounceController.php
  app/Http/Controllers/Auth/ActivationController.php
  app/Http/Controllers/Auth/ApplicationController.php
  app/Http/Controllers/Auth/ForgotUsernameController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/TwoStepController.php
  app/Http/Controllers/BonusController.php
  app/Http/Controllers/BookmarkController.php
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/FollowController.php
  app/Http/Controllers/GraveyardController.php
  app/Http/Controllers/ImageController.php
  app/Http/Controllers/InviteController.php
  app/Http/Controllers/LikeController.php
  app/Http/Controllers/PlaylistController.php
  app/Http/Controllers/PlaylistTorrentController.php
  app/Http/Controllers/PostController.php
  app/Http/Controllers/PrivateMessageController.php
  app/Http/Controllers/ReportController.php
  app/Http/Controllers/RequestController.php
  app/Http/Controllers/SeedboxController.php
  app/Http/Controllers/Staff/ApplicationController.php
  app/Http/Controllers/Staff/ArticleController.php
  app/Http/Controllers/Staff/BackupController.php
  app/Http/Controllers/Staff/BanController.php
  app/Http/Controllers/Staff/CategoryController.php
  app/Http/Controllers/Staff/ChatRoomController.php
  app/Http/Controllers/Staff/ChatStatusController.php
  app/Http/Controllers/Staff/GiftController.php
  app/Http/Controllers/Staff/GroupController.php
  app/Http/Controllers/Staff/MassActionController.php
  app/Http/Controllers/Staff/ModerationController.php
  app/Http/Controllers/Staff/NoteController.php
  app/Http/Controllers/Staff/PageController.php
  app/Http/Controllers/Staff/TagController.php
  app/Http/Controllers/Staff/TypeController.php
  app/Http/Controllers/Staff/UserController.php
  app/Http/Controllers/SubscriptionController.php
  app/Http/Controllers/TopicController.php
  app/Http/Controllers/TorrentController.php
  app/Http/Controllers/UserController.php
  app/Http/Middleware/CheckIfAlreadyVoted.php
  app/Models/Language.php
  app/Models/User.php
  app/Notifications/NewComment.php
  app/Notifications/NewCommentTag.php
  app/Notifications/NewPost.php
  app/Traits/TwoStep.php
Labels: Refactor, Review

#1129 (Refactor) Count On Null
  app/Console/Commands/GitUpdater.php
  app/Helpers/LanguageCensor.php
  app/Helpers/TorrentTools.php
  app/Http/Controllers/API/ChatController.php
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/Staff/BackupController.php
  app/Repositories/ChatRepository.php
Labels: Refactor, Review

#1134 (Refactor) Simplify Useless Variables
  app/Console/Commands/DemoSeed.php
  app/Helpers/Markdown.php
  app/Helpers/MediaInfo.php
  app/Models/Post.php
  app/Models/Torrent.php
  app/Models/UserNotification.php
  app/Models/UserPrivacy.php
  app/Services/Clients/OmdbClient.php
  app/Services/Clients/TmdbClient.php
  app/Traits/Encryptable.php
  app/Traits/TwoStep.php
Labels: Refactor, Review

#1136 (Refactor) Combine Nested Ifs
  app/Bots/SystemBot.php
  app/Console/Commands/AutoPreWarning.php
  app/Console/Commands/AutoWarning.php
  app/Http/Controllers/AnnounceController.php
  app/Http/Controllers/BonusController.php
  app/Http/Controllers/TorrentController.php
  app/Http/Middleware/TwoStepAuth.php
  app/Repositories/TaggedUserRepository.php
  app/Services/Clients/TmdbClient.php
  app/Traits/Auditable.php
Labels: Refactor, Review

#1140 (Refactor) Array Push To Array Assign
  app/Helpers/Bencode.php
  app/Helpers/LanguageCensor.php
  app/Services/Data/Movie.php
Labels: Refactor, Review

#1145 (Refactor) Simplify If Else To Ternary
  app/Bots/SystemBot.php
  app/Http/Controllers/API/ChatController.php
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/PrivateMessageController.php
  app/Http/Controllers/RequestController.php
  app/Http/Controllers/Staff/ForumController.php
  app/Http/Controllers/Staff/PollController.php
  app/Http/Controllers/TopicLabelController.php
  app/Http/Controllers/TorrentController.php
  app/Http/Controllers/UserController.php
  app/Models/Forum.php
Labels: Refactor, Review

#1146 (Refactor) Unnecessary Ternary Expression
  app/Http/Controllers/AnnounceController.php
  app/Http/Controllers/Staff/BackupController.php
  app/Http/Controllers/Staff/ForumController.php
  app/Http/Controllers/Staff/VersionController.php
  app/Models/Torrent.php
  app/Repositories/WishRepository.php
Labels: Refactor, Review

#1130 Adjust logic for poll.
  app/Http/Controllers/PollController.php
  resources/views/poll/forms/vote.blade.php
Labels: Enhancement, Review

#1155 (Refactor) Use Identical Over Equal With Same Type
  app/Bots/CasinoBot.php
  app/Bots/NerdBot.php
  app/Bots/SystemBot.php
  app/Helpers/Bencode.php
  app/Helpers/MediaInfo.php
  app/Helpers/StringHelper.php
  app/Helpers/TorrentTools.php
  app/Http/Controllers/API/ChatController.php
  app/Http/Controllers/API/TorrentController.php
  app/Http/Controllers/LanguageController.php
  app/Http/Controllers/PlaylistController.php
  app/Http/Controllers/Staff/BackupController.php
  app/Http/Controllers/Staff/UserController.php
  app/Http/Controllers/SubscriptionController.php
  app/Http/Controllers/TorrentController.php
  app/Http/Controllers/UserController.php
  app/Models/Language.php
  app/Models/Poll.php
  app/Models/User.php
  app/Services/Clients/TmdbClient.php
Labels: Refactor, Review

#1156 (Refactor) Simplify If Return Bool
  app/Models/Group.php
  app/Models/User.php
  app/Repositories/TaggedUserRepository.php
  app/Services/Clients/TmdbClient.php
  app/Traits/TwoStep.php
Labels: Refactor, Review

#1172 (Tests) Staff Controllers
  tests/Feature/Http/Controllers/Staff/ArticleControllerTest.php
  tests/Feature/Http/Controllers/Staff/CategoryControllerTest.php
  tests/Feature/Http/Controllers/Staff/ChatBotControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/ArticleControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/CategoryControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/ChatBotControllerTest.php
Labels: Review, Tests

#1175 (Tests) Staff Controllers
  database/factories/ChatroomFactory.php
  routes/web.php
  tests/Feature/Http/Controllers/Staff/ArticleControllerTest.php
  tests/Feature/Http/Controllers/Staff/CategoryControllerTest.php
  tests/Feature/Http/Controllers/Staff/ChatBotControllerTest.php
  tests/Feature/Http/Controllers/Staff/ChatRoomControllerTest.php
  tests/Feature/Http/Controllers/Staff/ChatStatusControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/ChatRoomControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/ChatStatusControllerTest.php
Labels: Review, Tests

#1176 (Tests) Staff Controllers
  tests/Feature/Http/Controllers/Staff/CheaterControllerTest.php
  tests/Feature/Http/Controllers/Staff/GiftControllerTest.php
  tests/Feature/Http/Controllers/Staff/GroupControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/CheaterControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/GiftControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/GroupControllerTest.php
Labels: Tests

#1178 (Tests) Console Commands
  .env.testing
  .travis.yml
  app/Console/Commands/AutoBan.php
  app/Console/Commands/AutoBonAllocation.php
  app/Console/Commands/AutoCorrectHistory.php
  app/Console/Commands/AutoDeactivateWarning.php
  app/Console/Commands/AutoDisableInactiveUsers.php
  app/Console/Commands/AutoFlushPeers.php
  app/Console/Commands/AutoGraveyard.php
  app/Console/Commands/AutoGroup.php
  app/Console/Commands/AutoHighspeedTag.php
  app/Console/Commands/AutoNerdStat.php
  app/Console/Commands/AutoPreWarning.php
  app/Console/Commands/AutoRecycleAudits.php
  app/Console/Commands/AutoRecycleClaimedTorrentRequests.php
  app/Console/Commands/AutoRecycleFailedLogins.php
  app/Console/Commands/AutoRecycleInvites.php
  app/Console/Commands/AutoRemoveFeaturedTorrent.php
  app/Console/Commands/AutoRemovePersonalFreeleech.php
  app/Console/Commands/AutoRevokePermissions.php
  app/Console/Commands/AutoSoftDeleteDisabledUsers.php
  app/Console/Commands/AutoWarning.php
  app/Console/Commands/DemoSeed.php
  app/Console/Commands/FetchGenres.php
  app/Console/Commands/FetchReleaseYears.php
  app/Console/Commands/SyncPeers.php
  composer.lock
  database/factories/TorrentFactory.php
  tests/Todo/Unit/Console/Commands/AutoNerdStatTest.php
  tests/Todo/Unit/Console/Commands/AutoRevokePermissionsTest.php
  tests/Todo/Unit/Console/Commands/FetchGenresTest.php
  tests/Todo/Unit/Console/Commands/FetchReleaseYearsTest.php
  tests/Todo/Unit/Console/Commands/GitUpdaterTest.php
  tests/Todo/Unit/Console/Commands/TestMailSettingsTest.php
  tests/Todo/Unit/Console/Commands/VendorCleanupTest.php
  tests/Unit/Console/Commands/AutoBanTest.php
  tests/Unit/Console/Commands/AutoBonAllocationTest.php
  tests/Unit/Console/Commands/AutoCorrectHistoryTest.php
  tests/Unit/Console/Commands/AutoDeactivateWarningTest.php
  tests/Unit/Console/Commands/AutoDisableInactiveUsersTest.php
  tests/Unit/Console/Commands/AutoFlushPeersTest.php
  tests/Unit/Console/Commands/AutoGraveyardTest.php
  tests/Unit/Console/Commands/AutoGroupTest.php
  tests/Unit/Console/Commands/AutoHighspeedTagTest.php
  tests/Unit/Console/Commands/AutoPreWarningTest.php
  tests/Unit/Console/Commands/AutoRecycleAuditsTest.php
  tests/Unit/Console/Commands/AutoRecycleClaimedTorrentRequestsTest.php
  tests/Unit/Console/Commands/AutoRecycleFailedLoginsTest.php
  tests/Unit/Console/Commands/AutoRecycleInvitesTest.php
  tests/Unit/Console/Commands/AutoRemoveFeaturedTorrentTest.php
  tests/Unit/Console/Commands/AutoRemovePersonalFreeleechTest.php
  tests/Unit/Console/Commands/AutoSoftDeleteDisabledUsersTest.php
  tests/Unit/Console/Commands/AutoWarningTest.php
  tests/Unit/Console/Commands/ClearCacheTest.php
  tests/Unit/Console/Commands/SetCacheTest.php
  tests/Unit/Console/Commands/SyncPeersTest.php
Labels: Tests

#1180 (Tests) Staff Controllers
  tests/Feature/Http/Controllers/Staff/CommandControllerTest.php
  tests/Feature/Http/Controllers/Staff/InviteControllerTest.php
  tests/Feature/Http/Controllers/Staff/NoteControllerTest.php
  tests/Feature/Http/Controllers/Staff/PageControllerTest.php
  tests/Feature/Http/Controllers/Staff/TypeControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/CommandControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/InviteControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/NoteControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/PageControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/TypeControllerTest.php
Labels: Tests
