Repository HDInnovations/UNIT3D, pull requests merged in 2020-03, with the labels that each got.

#1200 (Tests) Staff MassActionController.php
  app/Http/Controllers/Staff/MassActionController.php
  tests/Feature/Http/Controllers/Staff/MassActionControllerTest.php
  tests/Todo/Feature/Http/Controllers/Staff/MassActionControllerTest.php
Labels: Review, Tests

#1209 (Refactor) Change Read Only Property With Default Value To Constant
  app/Helpers/MediaInfo.php
  app/Services/Clients/TmdbClient.php
Labels: Refactor, Review

#1247 (Enhancement) New options on torrent upload api
  app/Http/Controllers/API/TorrentController.php
  tests/Feature/Http/Controllers/API/TorrentControllerTest.php
Labels: Enhancement
